site_name: Lunarc Documentation
pages:
- Home: index.md
- How to login: login_howto.md
- Quick reference: quick_reference.md
- Using the Job submission system: batch_system.md
- Using the Lunarc HPC Desktop: using_hpc_desktop.md
- Aurora Software: aurora_modules.md
- Compiler options: compiler_options.md
- Starting the DDT debugger on Alarik and Erik: ddt_debugger.md
- Batch system rules: batch_system_rules.md
- Linux Basics: linux_basics.md
theme: readthedocs
#markdown_extensions: [codehilite]