site_name: LUNARC Documentation
nav:
- Home: index.md
- Logging in:
  - How to login: login_howto.md
  - Activating Pocket Pass authenticator: authenticator_howto.md
- LUNARC HPC Desktop:
  - Using the LUNARC HPC Desktop: using_hpc_desktop.md
  - Graphical application launcher: gfxlauncher.md
- User's guide:
  - Using installed software on Aurora: aurora_modules.md
  - Using the Job submission system: batch_system.md
  - Quick reference: quick_reference.md
  - Using the lu32-partition: cascadelake_user.md
  - Linux Basics: linux_basics.md
- Aurora FAQ: aurora_faq.md
- Specific topics:
  - PYTHON on the cluster: Python.md
  - R on the cluser: Rscript.md
  - MATLAB on the cluster: MATLAB.md
  - ABAQUS on the cluster: Abaqus.md
  - COMSOL on the cluster: COMSOL.md
  - Compiler options: compiler_options.md
  - DDT debugger on Aurora: ddt_debugger.md
theme: 
  name: readthedocs
#markdown_extensions: [codehilite]
