site_name: LUNARC Documentation
nav:
- Home: index.md
- Getting started:
  - Creating a password for your account: getting_started/login_password.md
  - Activating Pocket Pass authenticator: getting_started/authenticator_howto.md
  - How to login: getting_started/login_howto.md
  - Transferring files: getting_started/transferring_files.md
  - Accessing the LUNARC HPC Desktop: getting_started/using_hpc_desktop.md
  - On-demand applications: getting_started/gfxlauncher.md
- FAQ: 
  - Login: faq/faq_login.md
  - Files: faq/faq_files.md
  - Jobs: faq/faq_jobs.md
  - Software: faq/faq_software.md 
- Manual:
  - Submitting jobs:
    - SLURM resource manager: users_guide/users_guide_intro.md
    - A basic job: users_guide/users_guide_small_job.md
    - Specifying job requirements: users_guide/users_guide_resource_all.md
    - Job requirements for multiprocessor jobs: users_guide/users_guide_resource_multiproc.md
    - Job execution environment: users_guide/users_guide_env.md
    - Using local disk to improve I/O performance: users_guide/users_guide_local_disk.md
    - Running MPI jobs: users_guide/users_guide_mpi_jobs.md
    - Controlling and monitoring jobs: users_guide/users_guide_job_control.md
  - Interactive node access: users_guide/users_guide_interactive.md
  - Using installed software: users_guide/users_guide_modules.md
  - Compiling code and using toolchains: users_guide/users_guide_modules_toolchains.md
  - Example jobs scripts:
    - Basic serial jobs: users_guide/users_guide_example_basic_1.md
    - Multiple serial jobs: users_guide/users_guide_example_multi_serial_1.md
    - MPI job using 20 tasks per node: users_guide/users_guide_example_mpi_1.md
    - MPI job using the node local discs: users_guide/users_guide_example_mpi_2.md
    - MPI jobs using fewer than 20 tasks per node: users_guide/users_guide_example_mpi_3.md
    - OpenMP jobs using shared memory: users_guide/users_guide_example_openmp_1.md
    - Hybrid-jobs using threads within an MPI framework: users_guide/users_guide_example_openmp_2.md
  - Batch system rules: users_guide/users_guide_rules.md
  - Quick reference: users_guide/users_guide_quick_reference.md
- Guides: 
  - Introduction: guides/intro.md
  - Linux Basics: 
    - Introduction to Linux: guides/linux/linux_basics_intro.md
    - An introduction to Linux shells and commands: guides/linux/linux_basics_shell_params.md
    - Files and directories in Linux: guides/linux/linux_basics_files.md
    - Special Command Symbols: guides/linux/linux_basics_special_symbols.md
    - Useful Linux commands: guides/linux/linux_basics_misc.md
  - Specific applications:
    - Python: guides/python/Python.md
    - MATLAB: guides/matlab/MATLAB.md
    - Abaqus FEA: guides/abaqus/Abaqus.md
    - COMSOL: guides/comsol/COMSOL.md
  - Transferring data:
    - Wget and Curl: guides/data_transfer/io_wget_curl.md
    - SFTP: guides/data_transfer/io_sftp.md
    - WinSCP: guides/data_transfer/io_winscp.md
    - Cyberduck: guides/data_transfer/io_cyberduck.md
    - Mounting Swestore: guides/data_transfer/swestore_mounting.md
    - Rclone and Swestore: guides/data_transfer/swestore_rclone.md
  - Software development:
    - Compiler options: guides/compiler/compiler_options.md
    - DDT debugger on Aurora: guides/debugging/ddt_debugger.md
  - Misc guides:
    - Using the 32-core nodes: guides/misc/cascadelake_user.md
- Links:
  - Web resources: links/links_web.md
  - Video resources: links/links_video.md
  - Social media: links/links_social.md 
- About: about/about.md

theme: 
  name: material
  palette:
    scheme: youtube
    #primary: LU
    #accent: LU
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant    
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - header.autohide
extra_css:
  - stylesheets/extra.css   

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta

