site_name: Lunarc Documentation
pages:
- Home: index.md
- How to login: login_howto.md
- Quick reference: quick_reference.md
- Batch system: batch_system.md
- Aurora Software: aurora_modules.md
theme: readthedocs