site_name: LUNARC Documentation
nav:
- Home: index.md
- Forgot your password?: intro/lost_password.md
- Getting started: 
  - Creating a password for your account: getting_started/login_password.md
  - Activating Pocket Pass authenticator: getting_started/authenticator_howto.md
  - How to login: getting_started/login_howto.md
  - Transferring files: getting_started/transferring_files.md
  - Accessing the LUNARC HPC Desktop: getting_started/using_hpc_desktop.md
  - On-demand applications: getting_started/gfxlauncher.md
- Manual:
  - Introduction: manual/manual_intro.md
  - Submitting jobs:
    - A basic job: manual/submitting_jobs/manual_basic_job.md
    - Specifying job requirements: manual/submitting_jobs/manual_specifying_requirements.md
    - Job requirements for multiprocessor jobs: manual/submitting_jobs/manual_requirements_multiproc.md
    - Job execution environment: manual/submitting_jobs/manual_env.md
    - Using local disk to improve I/O performance: manual/submitting_jobs/manual_local_disk.md
    - Running MPI jobs: manual/submitting_jobs/manual_mpi_jobs.md
    - Controlling and monitoring jobs: manual/submitting_jobs/manual_job_control.md
  - Interactive node access: manual/manual_interactive.md
  - Using installed software: manual/manual_modules.md
  - Compiling code and using toolchains: manual/manual_modules_toolchains.md
  - Example jobs scripts:
    - Basic serial jobs: manual/example_job_scripts/manual_example_basic_serial.md
    - Multiple serial jobs: manual/example_job_scripts/manual_example_multiple_serial_jobs.md
    - MPI job using 20 tasks per node: manual/example_job_scripts/manual_example_mpi_20_tasks.md
    - MPI job using the node local discs: manual/example_job_scripts/manual_example_mpi_local_discs.md
    - MPI jobs using fewer than 20 tasks per node: manual/example_job_scripts/manual_example_mpi_fewer_than_20.md
    - OpenMP jobs using shared memory: manual/example_job_scripts/manual_example_openmp_shared_memory.md
    - Hybrid-jobs using threads within an MPI framework: manual/example_job_scripts/manual_example_openmp_hybrid_jobs.md
  - Batch system rules: manual/manual_rules.md
  - Quick reference: manual/manual_quick_reference.md
  - FAQ: 
    - Login: manual/faq/manual_faq_login.md
    - Files: manual/faq/manual_faq_files.md
    - Jobs: manual/faq/manual_faq_jobs.md
    - Software: manual/faq/manual_faq_software.md 
  - Phrases and terms: manual/manual_common_phrases.md
- Guides:
  - Introduction: guides/guides_intro.md
  - Linux Basics: 
    - Introduction to Linux: guides/linux/linux_basics_intro.md
    - An introduction to Linux shells and commands: guides/linux/linux_basics_shell_params.md
    - Files and directories in Linux: guides/linux/linux_basics_files.md
    - Special Command Symbols: guides/linux/linux_basics_special_symbols.md
    - Useful Linux commands: guides/linux/linux_basics_misc.md
  - Transferring data:
    - Wget and Curl: guides/data_transfer/io_wget_curl.md
    - SFTP: guides/data_transfer/io_sftp.md
    - WinSCP: guides/data_transfer/io_winscp.md
    - Mounting Swestore: guides/data_transfer/swestore_mounting.md
    - Requesting a certificate for Swestore: guides/data_transfer/swestore_certificate.md
    - Using ARC to access Swestore: guides/data_transfer/swestore_arc.md
    - Rclone and Swestore: guides/data_transfer/swestore_rclone.md
    - Swestore links: guides/data_transfer/swestore_links.md
  - Batch system guides:
    - Using the 32-core nodes: guides/batch_system/32_core_nodes.md
  - Specific applications:
    - Python: guides/applications/Python.md
    - MATLAB: guides/applications/MATLAB.md
    - Abaqus FEA: guides/applications/Abaqus.md
    - COMSOL: guides/applications/COMSOL.md
  - Software development:
    - Compiler options: guides/software_development/compiler_options.md
    - DDT debugger on Aurora: guides/software_development/ddt_debugger.md
- Links:
  - Web resources: links/links_web.md
  - Video resources: links/links_video.md
  - Social media: links/links_social.md 
- About:
  - Contact: about/contact.md
  - LUNARC Documentation: about/about_documentation.md
  - HPC Ambassadors: about/ambassadors.md
  - Test page: about/testpage.md
  - Template: about/template.md

theme: 
  name: material
  palette:
    scheme: youtube
    #primary: LU
    #accent: LU
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant    
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - header.autohide
extra_css:
  - stylesheets/extra.css   

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js 

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta

