site_name: LUNARC Documentation
nav:
- Home: index.md
- Getting started:
  - How to login: login_howto.md
  - Activating Pocket Pass authenticator: authenticator_howto.md
  - The LUNARC HPC Desktop: using_hpc_desktop.md
  - On-demand applications: gfxlauncher.md
- User's guide:
  - Using installed software: aurora_modules.md
  - Using the Job submission system: batch_system.md
  - Using the lu32-partition: cascadelake_user.md
  - Quick reference: quick_reference.md
- FAQ: 
  - Login: faq_login.md
  - Files: faq_files.md
  - Jobs: faq_jobs.md
  - Software: faq_software.md 
- Specific topics:
  - Linux Basics: linux_basics.md
  - Compiler options: compiler_options.md
  - DDT debugger on Aurora: ddt_debugger.md
- Applications:
  - Python: Python.md
  - MATLAB: MATLAB.md
  - Abaqus FEA: Abaqus.md
  - COMSOL: COMSOL.md
theme: 
  name: material
  palette:
    scheme: youtube
    #primary: LU
    #accent: LU
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant    
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - header.autohide
extra_css:
  - stylesheets/extra.css    
#markdown_extensions: [codehilite]
